spring:
  application:
    name: ImoocMerchants
  datasource:
    url: spring.datasource.url=jdbc:mysql://118.25.209.40:3306/passbook?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
    username: root
    password: dengkunchen

  kafka:
    bootstrap-servers: 118.25.209.40:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4

  data:
      hbase:
        quorum: 127.0.0.1:2181
        rootDir: file:///home/kkc/imooc/hbase_data/root_dir
        nodeParent: /hbase

  redis:
    host: 118.25.209.40
    port: 6379

server:
  port: 9528

logging:
  level: debug:true
  file: imooc-passbook.log
